#cloud-config
package_update: true
package_upgrade: true
packages:
  - curl
  - wget
  - git
  - net-tools
  - zip
  - unzip
  - apparmor-utils
  - ca-certificates
  - cloud-guest-utils
  - cloud-image-utils
  - cloud-initramfs-growroot
  - open-iscsi
  - nfs-common
  - openssh-server
  - open-vm-tools
